{
 "title": "Retail Store — RED Metrics",
 "description": "Rate, Errors, and Duration (RED method) for retail store microservices.\nCovers UI, Cart, Orders (Spring Boot), and Catalog (Go). SLO monitoring\ndashboard for detecting production issues in real-time.",
 "tags": [
  "retail-store",
  "RED"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": " UI — Rate (req/s)",
   "type": "timeseries",
   "description": "Requests per second handled by UI service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"ui\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UI — Avg Latency",
   "type": "timeseries",
   "description": "Latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"ui\"}[5m]))\r\n/\r\nsum(rate(http_server_requests_seconds_count{job=\"ui\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UI — Error Rate (%)",
   "type": "stat",
   "description": "Error handled by UI service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"ui\",status=~\"5..\"}[5m]))\r\n/\r\nsum(rate(http_server_requests_seconds_count{job=\"ui\"}[5m]))\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}